### PR TITLE
LICENSE VIOLATION

### PR DESCRIPTION
**Pull request by RavenSystem**
I have created this issue here because you have disabled "issues" part in this repo.

You are using source code from several public repositories without complying with their respective license agreements. You do not public your source code, you do not mention the original authors, you do not include their license agreements in your repository, you do not provide any information about the original repositories, and you are asking people for money to get your source code. For all these reasons, you should leave your activity and remove this repo.

https://github.com/maximkulkin/esp-homekit
https://github.com/maximkulkin/esp-homekit-demo
https://github.com/maximkulkin/esp-wifi-config

These logs from your firmware are the evidence, and there are a lot of binary coincidences too:
```
>>> wifi_config: wifi_config_sta_connect_timeout_callback: Timeout connecting to WiFi network, starting config AP
>>> wifi_config: Starting AP mode
mode : sta(dc:4f:22:4b:75:26) + softAP(de:4f:22:4b:75:26)
add if0
add if1
bcn 100
Function called without core lock
>>> wifi_config: wifi_config_softap_start: Starting AP SSID=sonoff-switch-4B7526
bcn 0
del if1
add if1
bcn 100
>>> wifi_config: Starting DHCP server
>>> wifi_config: Starting WiFi scan
>>> wifi_config: Starting DNS server
>>> wifi_config: Staring HTTP server
scandone
scandone
scandone
scandone
scandone
add 1
aid 1
station: 78:7b:8a:2f:39:03 join, AID = 1
>>> wifi_config: http_task: Got 64 incomming data
!!! wifi_config: Unknown endpoint: GET /hotspot-detect.html
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 5 incomming data
>>> wifi_config: wifi_config_server_on_message_complete: Unknown endpoint
>>> wifi_config: client_send_redirect: Redirecting to http://192.168.4.1/settings
>>> wifi_config: Client disconnected
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 52 incomming data
>>> wifi_config: Client disconnected
>>> wifi_config: http_task: Got 64 incomming data
!!! wifi_config: Unknown endpoint: GET /hotspot-detect.html
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 49 incomming data
>>> wifi_config: wifi_config_server_on_message_complete: Unknown endpoint
>>> wifi_config: client_send_redirect: Redirecting to http://192.168.4.1/settings
>>> wifi_config: Client disconnected
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 32 incomming data
>>> wifi_config: Client disconnected
>>> wifi_config: http_task: Got 64 incomming data
!!! wifi_config: Unknown endpoint: GET /hotspot-detect.html
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 5 incomming data
>>> wifi_config: wifi_config_server_on_message_complete: Unknown endpoint
>>> wifi_config: client_send_redirect: Redirecting to http://192.168.4.1/settings
>>> wifi_config: Client disconnected
>>> wifi_config: http_task: Got 64 incomming data
>>> wifi_config: http_task: Got 52 incomming data
scandone
>>> wifi_config: Client disconnected
```

```
>>> HomeKit: Starting server
>>> HomeKit: Formatting flash at 0x7a000
>>> HomeKit: Generated new accessory ID: CF:14:69:47:AF:7C
>>> HomeKit: Generated new accessory key
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
>>> HomeKit: Configuring mDNS
mDNS announcement: Name=Sonoff Switch-4B7526md=Basicpv=1.0id=CF:14:69:47:AF:7Cc#=1s#=1ff=0sf=1ci=8 Port=5556 TTL=4500
```

Best regards.

### CODE REVIEW

**Comment by Gruppio** [comment]
Hi @RavenSystem I will fix all the issues ASAP

**Comment by 5p4k** [comment]
@Gruppio You are still in violation of the license. As per section _6. Conveying Non-Source Forms._, you may not convey object code without giving the users access to the corresponding source code. Specifically, you state that you will release access to the source only upon donation, which is an open violation of section 6c, since you received the source code that you base your work on for free and you are releasing it commercially.

I am here because I tried your software but it does not work for me. Issues are disabled so was going to debug it myself.

**Comment by smartynov** [comment]
I totally agree and support this opinion: either you're following the open-source world standards and enjoying it, or you leave this universe and live somewhere else. Please decide.

**Comment by RavenSystem** [comment]
IMO, a DMCA Takedown is necessary here...

**Comment by YerBabiE** [comment]
I was going to donate some funds, and request a code update, but it appears you don't deserve it.... address the issues and have some respect man.....

**Comment by joaodforce** [comment]
@RavenSystem Excuse me, but I don't think you are making too much sense here. All three of the projects listed are under MIT license

https://github.com/maximkulkin/esp-homekit
https://github.com/maximkulkin/esp-homekit-demo
https://github.com/maximkulkin/esp-wifi-config

Which allows distribution without providing sources, also the product is not blocked behind a pay wall, the Owner accepts donations in exchange of basic support. Practice that is common on many other Open Source Projects.

The only thing I found so far that uses GPL is the toolchain 

https://github.com/pfalcon/esp-open-sdk#license

The ladder of which only requires Sources if you are redistributing the toolchain itself, that is not included on the project.

I am open to new information however, if you provide better information about what License from what projects are being violated I would be happy to agree with your points.

**Pull request closed without merging**
